name: Lint

on:
  push:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prepare (lint)
        run: "yarn install"
      - name: Check (lint)
        run: "yarn lint"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Prepare (build)
        run: "yarn install"
      - name: Check (build)
        run: "yarn build"
